### ISSUE TITLE
add 'Localization group information' block to group page

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-ops/localization#19]
We would need the 'Localization group information' block to be shown in a language group, otherwise no one can join. I need to join the catalan group but cannot.

**Comment by olafgrabienski** [comment]
@robertgarrigos The block is enabled. You can't join the group because there is no catalan group so far (the page you see, has been created by adding the catalan language, but without group functionality). However, as you are a "groups manager", you should be able to create the new catalan localization group by yourself. Can you give it a try?

**Comment by robertgarrigos** [comment]
Thanks @olafgrabienski I couldn't see the admin menu bar. I have created the Catalan group.

**Comment by olafgrabienski** [comment]
You're welcome! Re admin menu bar: was it a temporary problem, or does it persist?
