### ISSUE TITLE
Responsive website theme

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/localization#26]
The website layout isn't responsive so far. It uses the core *Bartik* theme. To make it responsive, I suggest to use the contributed D7 theme [Responsive Bartik](https://www.drupal.org/project/responsive_bartik).

I've used *Responsive Bartik* on a couple of D7 sites. It's easy to set up and works well. In my opinion the easiest way to make the site layout responsive.

**Comment by jenlampton** [comment]
I've added the responsive bartik theme to the site. 

IIRC, when you change themes, all the settings are lost. We may need to visit the theme settings page and note all the color settings before making the change, so that we have all the information handy when you need to set it again.

Or better yet, let's take a picture: 
![bartik-settings](https://user-images.githubusercontent.com/397895/52524789-e3f77b00-2c55-11e9-93a5-d7161fd453f1.png)

**Comment by olafgrabienski** [comment]
Thanks for installing the module and making the picture of the settings (good point)!

I've enabled *Responsive Bartik*, changed the settings to match the ones of *Bartik*, and set *Responsive Bartik* as default theme.
