### ISSUE TITLE
Upgrade Translation server to Backdrop

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/localization#45]
The Translation server is running on Drupal 7 which will reach [end-of-live in November ~~2022~~ 2023](https://www.drupal.org/psa-2022-02-23) . Let's upgrade the site to Backdrop before D7 EOL!

More details upcoming, e.g.

- List general challenges and make a plan.
- Check which key modules are ported or underway, and which are not.
- Schedule some sprints to do the upgrade.

**Comment by argiepiano** [comment]
I'm able to gives this a try. I think the easiest way is to fork the repo and install the site in my local, then proceed from there to either migrate the site, or rebuild it in Backdrop. But in order to do that  I'd need access to the current database and translation files. I see that `backup_migrate` is among the modules in the `sites/all/modules` folder. So, I could log in the site and, with the appropriate permissions, download a db dump using that module.  At the moment, it looks like I don't have login access yet. 

Let me know if this sounds good to y'all.

**Comment by jenlampton** [comment]
@argiepiano once the site is in Backdrop, we should switch to [the borg theme](https://github.com/backdrop-contrib/borg). I'd be happy to help move over any customizations that are specific to the localize site when that happens.

**Comment by argiepiano** [comment]
Sounds good. I'll try applying the Borg theme to the current test site to see if there are any issues.

**Comment by olafgrabienski** [comment]
Last weekend the Translation site has been upgraded to Backdrop. Many thanks @argiepiano and @jenlampton!

(Closing this issue.)
